# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"device_error": "00_torch.ipynb",
         "hook_fn": "00_torch.ipynb",
         "PreHook": "00_torch.ipynb",
         "ForwardHooks": "00_torch.ipynb",
         "hook_outputs": "00_torch.ipynb",
         "layer_error": "00_torch.ipynb",
         "collate_error": "01_fastai.dataloader.ipynb",
         "DataLoader.create_batch": "01_fastai.dataloader.ipynb",
         "TfmdDL.new": "03_fastai.transform.ipynb",
         "loss_func_error": "02_fastai.learner.ipynb",
         "callback_error": "02_fastai.learner.ipynb",
         "catch_pred_errors": "02_fastai.learner.ipynb",
         "catch_loss_errors": "02_fastai.learner.ipynb",
         "Learner.sanity_check": "02_fastai.learner.ipynb",
         "Learner.__init__": "02_fastai.learner.ipynb",
         "module_error": "02_fastai.learner.ipynb",
         "load_learner": "02_fastai.learner.ipynb",
         "transform_error": "03_fastai.transform.ipynb",
         "Transform.__call__": "03_fastai.transform.ipynb",
         "Transform.decode": "03_fastai.transform.ipynb",
         "TfmdLists.__init__": "04_fastai.datasets.ipynb",
         "subset_error": "04_fastai.datasets.ipynb",
         "TfmdLists.subset": "04_fastai.datasets.ipynb",
         "TfmdLists.setup": "04_fastai.datasets.ipynb"}

modules = ["torch.py",
           "fastai/dataloader.py",
           "fastai/learner.py",
           "fastai/transform.py",
           "fastai/datasets.py"]

doc_url = "https://muellerzr.github.io/fastdebug/"

git_url = "https://github.com/muellerzr/fastdebug/tree/master/"

def custom_doc_links(name): return None
