# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"device_error": "00_torch.ipynb",
         "hook_fn": "00_torch.ipynb",
         "PreHook": "00_torch.ipynb",
         "ForwardHooks": "00_torch.ipynb",
         "hook_outputs": "00_torch.ipynb",
         "layer_error": "00_torch.ipynb",
         "collate_error": "01_fastai.data.ipynb",
         "DataLoader.create_batch": "01_fastai.data.ipynb",
         "loss_func_error": "02_fastai.learner.ipynb",
         "callback_error": "02_fastai.learner.ipynb",
         "catch_pred_errors": "02_fastai.learner.ipynb",
         "catch_loss_errors": "02_fastai.learner.ipynb",
         "Learner.sanity_check": "02_fastai.learner.ipynb",
         "Learner.__init__": "02_fastai.learner.ipynb"}

modules = ["torch.py",
           "fastai/dataloader.py",
           "fastai/learner.py"]

doc_url = "https://muellerzr.github.io/fastdebug/"

git_url = "https://github.com/muellerzr/fastdebug/tree/master/"

def custom_doc_links(name): return None
