# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"device_error": "00_error.torch.ipynb",
         "hook_fn": "00_error.torch.ipynb",
         "PreHook": "00_error.torch.ipynb",
         "ForwardHooks": "00_error.torch.ipynb",
         "hook_outputs": "00_error.torch.ipynb",
         "layer_error": "00_error.torch.ipynb",
         "loss_func_error": "01_error.fastai.ipynb",
         "callback_error": "01_error.fastai.ipynb",
         "catch_pred_errors": "01_error.fastai.ipynb",
         "catch_loss_errors": "01_error.fastai.ipynb",
         "Learner.sanity_check": "01_error.fastai.ipynb",
         "Learner.__init__": "01_error.fastai.ipynb"}

modules = ["error/torch.py",
           "error/fastai.py"]

doc_url = "https://muellerzr.github.io/fastdebug/"

git_url = "https://github.com/muellerzr/fastdebug/tree/master/"

def custom_doc_links(name): return None
